-- MySQL Script generated by MySQL Workbench
-- Fri Oct  1 21:20:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema diagrama_er_grupal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `diagrama_er_grupal` ;

-- -----------------------------------------------------
-- Schema diagrama_er_grupal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diagrama_er_grupal` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `diagrama_er_grupal` ;

-- -----------------------------------------------------
-- Table `articulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `articulo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `articulo` (
  `id_articulo` INT NOT NULL,
  `stock` INT NOT NULL,
  `descripcion_articulo` VARCHAR(75) NULL,
  PRIMARY KEY (`id_articulo`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `numero_articulo_UNIQUE` ON `articulo` (`id_articulo` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cabecera_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cabecera_pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cabecera_pedido` (
  `id_pedido` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `direccion_envio` VARCHAR(45) NOT NULL,
  `fecha_pedido` DATE NOT NULL,
  PRIMARY KEY (`id_pedido`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `numero_pedido_UNIQUE` ON `cabecera_pedido` (`id_pedido` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cliente` (
  `id_cliente` INT NOT NULL,
  `saldo` INT NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `numero_cliente_UNIQUE` ON `cliente` (`id_cliente` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `detalle_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `detalle_pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `detalle_pedido` (
  `id_detalle_pedido` INT NOT NULL,
  `id_pedido` INT NOT NULL,
  `id_articulo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_detalle_pedido`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_detalle_pedido_UNIQUE` ON `detalle_pedido` (`id_detalle_pedido` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `direcciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `direcciones` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `direcciones` (
  `id_direccion` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_direccion`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `distribuidores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `distribuidores` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `distribuidores` (
  `id_distribuidor` VARCHAR(45) NOT NULL,
  `id_fabrica` INT NOT NULL,
  `telefono_contacto` VARCHAR(45) NOT NULL,
  `id_articulo` INT NOT NULL,
  PRIMARY KEY (`id_fabrica`, `id_distribuidor`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_fabrica_UNIQUE` ON `distribuidores` (`id_fabrica` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fabrica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fabrica` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fabrica` (
  `id_fabrica` INT NOT NULL,
  `nombre_fabrica` VARCHAR(45) NOT NULL,
  `id_articulo` INT NOT NULL,
  PRIMARY KEY (`id_fabrica`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_fabrica_UNIQUE` ON `fabrica` (`id_fabrica` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `diagrama_er_grupal`.`articulo`
(`id_articulo`,
`stock`,
`descripcion_articulo`)
VALUES
(2,15,'frenos'),
(3,30,'embragues');

INSERT INTO `diagrama_er_grupal`.`fabrica`
(`id_fabrica`,
`nombre_fabrica`,
`id_articulo`)
VALUES
(1,'pirelli',1),
(2,'michelin',1);
select*from fabrica;
alter table fabrica drop column id_articulo;

